variable "resource-group-name" {}
variable "frontdoor-name" {}
variable "frontdoor-RR-name" {}
variable "frontdoor-RR-accepted_protocols" {}
variable "frontdoor-RR-patterns_to_match" {}
variable "frontdoor-RR-frontend_endpoints" {}
variable "frontdoor-RR-forwarding_protocol" {}
variable "frontdoor-RR-backend_pool_name" {}
variable "frontdoor-BPLB-name" {}
variable "frontdoor-BPHP-name" {}
variable "frontdoor-BP-name" {}
variable "frontdoor-backend-host_header" {}
variable "frontdoor-backend-address" {}
variable "frontdoor-backend-http_port" {}
variable "frontdoor-backend-https_port" {}
variable "frontdoor-backend-load_balancing_name" {}
variable "frontdoor-backend-health_probe_name" {}
variable "frontdoor-FE-name" {}
variable "frontdoor-FE-host_name" {}
variable "frontdoor-FE-session_affinity_enabled" {}
variable "frontdoor-FE-session_affinity_ttl_seconds" {}